server:
  port: 9090
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rvivanco/config-server.git
          search-paths: MASTER
          username: rvivanco
          password: vivanco16+
